import { useEffect, useState } from 'react';
import { Modal } from './Modal';
import { unfence } from '../lib/domain/injection';
import { callTool } from '../lib/tools';
import { useSelectedDataset } from '../store/app-store';

const FORMATS = [
  { id: 'sql', label: 'SQL' },
  { id: 'python', label: 'pandas' },
  { id: 'dbt', label: 'dbt' },
  { id: 'json', label: 'JSON' },
  { id: 'great_expectations', label: 'Expectations' },
  // Not a pipeline format, but this is where a user looks for "give me
  // something to take away", so it belongs beside the others.
  { id: 'docs', label: 'Docs' },
] as const;

type Format = (typeof FORMATS)[number]['id'];

/**
 * Take the work with you.
 *
 * A cleaning session that only exists in one browser tab is a demo. The SQL is
 * generated by the same compiler that executed the steps, so this is the query
 * that ran — not a reimplementation that could quietly disagree with it.
 */
export function ExportPanel({ onClose }: { onClose: () => void }) {
  const dataset = useSelectedDataset();
  const [format, setFormat] = useState<Format>('sql');
  const [code, setCode] = useState('');
  const [steps, setSteps] = useState(0);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!dataset) return;
    let cancelled = false;

    (async () => {
      setLoading(true);
      setError(null);
      try {
        if (format === 'docs') {
          const result = (await callTool('generate_data_documentation', {
            dataset_id: dataset.id,
          })) as { documentation: string };
          if (cancelled) return;
          // The fence is for agents; a person reading the panel just wants the
          // document.
          setCode(unfence(result.documentation));
          setSteps(0);
          return;
        }

        const result = (await callTool('export_transformation_pipeline', {
          dataset_id: dataset.id,
          format,
        })) as { code: string; step_count: number };
        if (cancelled) return;
        setCode(result.code);
        setSteps(result.step_count);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [dataset, format]);

  async function copy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
  }

  return (
    <Modal
      title="Export pipeline"
      subtitle={
        format === 'docs'
          ? 'A data dictionary and methodology, generated from measured data'
          : `${steps} applied step${steps === 1 ? '' : 's'} · steps you undid are excluded`
      }
      onClose={onClose}
      height="h-[min(700px,86vh)]"
    >
      <div className="flex flex-col h-full">
        <div className="flex shrink-0 flex-wrap items-center gap-1 border-b border-ink-600 px-4 py-2">
          {FORMATS.map((f) => (
            <button
              key={f.id}
              onClick={() => setFormat(f.id)}
              className={`rounded-sm px-2.5 py-1 font-mono text-[11px] transition-colors ${
                format === f.id
                  ? 'bg-now-dim text-now'
                  : 'text-text-lo hover:bg-ink-700 hover:text-text-mid'
              }`}
            >
              {f.label}
            </button>
          ))}
          <div className="flex-1" />
          <button className="btn" onClick={() => void copy()} disabled={!code}>
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        <div className="min-h-0 flex-1 overflow-auto p-4">
          {loading && <CodeSkeleton />}
          {error && (
            <p role="alert" className="text-xs text-alarm">
              {error}
            </p>
          )}
          {!loading && !error && (
            <pre className="font-mono text-[11px] leading-relaxed whitespace-pre text-text-mid">
              {code}
            </pre>
          )}
        </div>
      </div>
    </Modal>
  );
}

/** Shaped like the code it replaces, so the panel does not jump on load. */
function CodeSkeleton() {
  const widths = ['w-2/3', 'w-1/2', 'w-5/6', 'w-1/3', 'w-3/4', 'w-2/5', 'w-4/5'];
  return (
    <div className="space-y-2" aria-busy="true" aria-label="Generating export">
      {widths.map((width, i) => (
        <div key={i} className={`h-3 animate-pulse rounded-sm bg-ink-700 ${width}`} />
      ))}
    </div>
  );
}
