import { useEffect, useState } from 'react';
import { callTool } from '../lib/tools';
import { useSelectedDataset } from '../store/app-store';

const FORMATS = [
  { id: 'sql', label: 'SQL' },
  { id: 'python', label: 'pandas' },
  { id: 'dbt', label: 'dbt' },
  { id: 'json', label: 'JSON' },
] as const;

type Format = (typeof FORMATS)[number]['id'];

/**
 * Take the work with you.
 *
 * A cleaning session that only exists in one browser tab is a demo. The SQL is
 * generated by the same compiler that executed the steps, so this is the query
 * that ran — not a reimplementation that could quietly disagree with it.
 */
export function ExportPanel({ onClose }: { onClose: () => void }) {
  const dataset = useSelectedDataset();
  const [format, setFormat] = useState<Format>('sql');
  const [code, setCode] = useState('');
  const [steps, setSteps] = useState(0);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!dataset) return;
    let cancelled = false;

    (async () => {
      setLoading(true);
      setError(null);
      try {
        const result = (await callTool('export_transformation_pipeline', {
          dataset_id: dataset.id,
          format,
        })) as { code: string; step_count: number };
        if (cancelled) return;
        setCode(result.code);
        setSteps(result.step_count);
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [dataset, format]);

  async function copy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink-900/80 p-6"
      onClick={onClose}
    >
      <div
        className="panel flex h-[min(700px,86vh)] w-full max-w-3xl flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-ink-600 px-4 py-3">
          <div>
            <div className="eyebrow">Export pipeline</div>
            <p className="mt-0.5 font-mono text-[10px] text-text-lo">
              {steps} applied step{steps === 1 ? '' : 's'} · steps you undid are excluded
            </p>
          </div>
          <button className="btn" onClick={onClose}>
            Close
          </button>
        </div>

        <div className="flex items-center gap-1 border-b border-ink-600 px-4 py-2">
          {FORMATS.map((f) => (
            <button
              key={f.id}
              onClick={() => setFormat(f.id)}
              className={`rounded-sm px-2.5 py-1 font-mono text-[11px] transition-colors ${
                format === f.id
                  ? 'bg-now-dim text-now'
                  : 'text-text-lo hover:bg-ink-700 hover:text-text-mid'
              }`}
            >
              {f.label}
            </button>
          ))}
          <div className="flex-1" />
          <button className="btn" onClick={() => void copy()} disabled={!code}>
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        <div className="min-h-0 flex-1 overflow-auto p-4">
          {loading && <p className="text-xs text-text-lo">Generating…</p>}
          {error && <p className="text-xs text-alarm">{error}</p>}
          {!loading && !error && (
            <pre className="font-mono text-[11px] leading-relaxed whitespace-pre text-text-mid">
              {code}
            </pre>
          )}
        </div>
      </div>
    </div>
  );
}
