import type { ColumnProfile } from '../engine/introspect';
import type { Dataset } from '../engine/registry';
import { toExcerpt } from './injection';
import type { Pipeline } from './pipeline';
import type { QualityIssue } from './quality/types';
import type { SemanticDetection } from './quality/semantics';

/**
 * Generate a data dictionary and methodology document.
 *
 * **No language model is involved, deliberately.** Every input is already
 * structured — the schema, the profile statistics, the transformation history,
 * the quality findings — so the document can be derived rather than written.
 * That means it works with no API key, costs nothing, is identical on every
 * run, and cannot invent a column description that sounds plausible and is
 * wrong. For documentation whose entire purpose is to be trusted, that last
 * property is worth more than fluent prose.
 *
 * Everything stated here is either measured or explicitly labelled as absent.
 */

const NL = String.fromCharCode(10);

export interface DocsInput {
  readonly dataset: Dataset;
  readonly profiles: readonly ColumnProfile[];
  readonly semantics: readonly SemanticDetection[];
  readonly issues: readonly QualityIssue[];
  readonly qualityScore: number;
  readonly pipeline: Pipeline;
  /** Omitted from output when absent, so the doc is reproducible in tests. */
  readonly generatedAt?: string;
  /**
   * Whether the column dictionary carries real example values.
   *
   * Those examples are raw cell content. In the app they are the most useful
   * column in the table; in anything that leaves the machine they are data
   * exfiltration wearing a helpful hat. Default true for the in-app view,
   * explicitly false for export.
   */
  readonly includeSamples?: boolean;
}

function pct(ratio: number): string {
  const v = ratio * 100;
  if (v === 0) return '0%';
  if (v < 0.1) return '<0.1%';
  return `${v.toFixed(v < 10 ? 1 : 0)}%`;
}

/** Escape pipes so a stray value cannot break the Markdown table. */
function cell(value: string): string {
  return toExcerpt(value, 60).replace(/\|/g, '\\|');
}

export function generateDocumentation(input: DocsInput): string {
  const { dataset, profiles, semantics, issues, pipeline } = input;
  const head = dataset.history[dataset.headIndex];
  const original = dataset.history[0];
  const semanticsByColumn = new Map(semantics.map((s) => [s.column, s]));

  const out: string[] = [];

  out.push(`# ${dataset.name}`);
  out.push('');
  out.push('Generated by DataSweep Pro. Every figure below is measured from the data.');
  if (input.generatedAt) out.push(`Generated ${input.generatedAt}.`);
  out.push('');

  // --- Overview ------------------------------------------------------------
  out.push('## Overview');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| Rows | ${(head?.rowCount ?? 0).toLocaleString()} |`);
  out.push(`| Columns | ${(head?.columns.length ?? 0).toLocaleString()} |`);
  out.push(`| Quality score | ${input.qualityScore}/100 |`);
  out.push(`| Cleaning steps applied | ${dataset.headIndex} |`);
  if (original && original.rowCount !== head?.rowCount) {
    out.push(
      `| Rows at load | ${original.rowCount.toLocaleString()} ` +
        `(${(original.rowCount - (head?.rowCount ?? 0)).toLocaleString()} removed by cleaning) |`,
    );
  }
  if (dataset.skippedRows > 0) {
    out.push(
      `| **Rows skipped at load** | **${dataset.skippedRows.toLocaleString()}** — could not be parsed |`,
    );
  }
  out.push('');

  // --- Column dictionary ---------------------------------------------------
  out.push('## Column dictionary');
  out.push('');
  const withSamples = input.includeSamples !== false;

  out.push(
    withSamples
      ? '| Column | Detected type | Confidence | Missing | Distinct | Example values |'
      : '| Column | Detected type | Confidence | Missing | Distinct |',
  );
  out.push(withSamples ? '|---|---|---|---|---|---|' : '|---|---|---|---|---|');

  for (const profile of profiles) {
    const semantic = semanticsByColumn.get(profile.column);
    const type = semantic ? semantic.label : profile.dataType;
    const confidence = semantic
      ? semantic.ambiguous
        ? 'ambiguous'
        : `${Math.round(semantic.confidence * 100)}%`
      : '—';
    const row =
      `| \`${cell(profile.column)}\` | ${type} | ${confidence} | ` +
      `${pct(profile.nullRate)} | ${profile.distinctCount.toLocaleString()} |`;

    out.push(withSamples ? `${row} ${profile.samples.map(cell).join(', ') || '—'} |` : row);
  }
  out.push('');

  if (!withSamples) {
    out.push('');
    out.push(
      'Example values are omitted from this copy: it was generated for export, and sample ' +
        'values are raw cell content.',
    );
  }
  out.push('');

  const ambiguous = semantics.filter((s) => s.ambiguous);
  if (ambiguous.length > 0) {
    out.push(
      `${ambiguous.length} column(s) could not be typed confidently and are marked ambiguous: ` +
        `${ambiguous.map((s) => `\`${s.column}\``).join(', ')}. ` +
        'Treat their contents as mixed until reviewed.',
    );
    out.push('');
  }

  // --- Quality -------------------------------------------------------------
  out.push('## Data quality');
  out.push('');
  if (issues.length === 0) {
    out.push('No outstanding quality issues were detected.');
  } else {
    out.push(`${issues.length} outstanding issue(s) at the time of writing.`);
    out.push('');
    out.push('| Severity | Type | Column | Rows affected | Detail |');
    out.push('|---|---|---|---|---|');
    for (const issue of issues) {
      out.push(
        `| ${issue.severity} | \`${issue.type}\` | ${issue.column ? `\`${cell(issue.column)}\`` : '—'} | ` +
          `${issue.affectedRows.toLocaleString()} | ${cell(issue.description)} |`,
      );
    }
  }
  out.push('');

  // --- Methodology ---------------------------------------------------------
  out.push('## How this data was cleaned');
  out.push('');
  if (pipeline.steps.length === 0) {
    out.push('No transformations have been applied. This is the data exactly as loaded.');
  } else {
    out.push(`${pipeline.steps.length} transformation(s), applied in this order:`);
    out.push('');
    pipeline.steps.forEach((step, i) => {
      const target = step.column ? ` on \`${cell(step.column)}\`` : ' on the whole table';
      out.push(`${i + 1}. **\`${step.operation}\`**${target} — ${step.description}`);
    });
    out.push('');
    out.push(
      'Every step was previewed and approved before it ran, and each produced a checkpoint ' +
        'that can be restored.',
    );
  }
  out.push('');

  // --- Limitations ---------------------------------------------------------
  // Stated unconditionally. A dictionary that only lists its strengths invites
  // exactly the over-trust that makes bad data dangerous.
  out.push('## Known limitations');
  out.push('');
  const limitations: string[] = [];

  if (dataset.skippedRows > 0) {
    limitations.push(
      `**${dataset.skippedRows} row(s) are missing entirely.** They could not be parsed at load ` +
        'and are not represented anywhere in this dataset or in these statistics.',
    );
  }
  for (const issue of issues.filter((i) => i.type === 'contradictory_date_order')) {
    limitations.push(
      `**\`${issue.column}\` mixes date orderings.** Some values are D/M/Y and others M/D/Y. ` +
        'No single interpretation is correct for the whole column; do not sort or compare it ' +
        'until this is resolved per row.',
    );
  }
  for (const step of pipeline.steps.filter((s) => s.operation === 'standardize_dates')) {
    limitations.push(
      `**\`${step.column}\` dates were normalized** using a ` +
        `${step.parameters['dayFirst'] === false ? 'month-first' : 'day-first'} reading. ` +
        'Values ambiguous under that reading were interpreted accordingly.',
    );
  }
  for (const step of pipeline.steps.filter((s) => s.operation === 'clip_outliers')) {
    limitations.push(
      `**\`${step.column}\` was clipped** to ${String(step.parameters['lower'])}–` +
        `${String(step.parameters['upper'])}. Values outside that range no longer reflect what ` +
        'was measured.',
    );
  }
  for (const semantic of ambiguous) {
    limitations.push(
      `**\`${semantic.column}\` has no confident type.** It is treated as text.`,
    );
  }

  if (limitations.length === 0) {
    limitations.push(
      'No transformation in this pipeline discards or reinterprets data, and no rows were ' +
        'lost at load.',
    );
  }
  for (const limitation of limitations) out.push(`- ${limitation}`);
  out.push('');

  // --- Usage ---------------------------------------------------------------
  out.push('## Recommended usage');
  out.push('');
  const identifiers = semantics.filter((s) => s.detectedType === 'identifier');
  const numerics = semantics.filter(
    (s) => s.detectedType === 'integer' || s.detectedType === 'decimal' || s.detectedType === 'currency',
  );

  if (identifiers.length > 0) {
    out.push(
      `- Join on ${identifiers.map((s) => `\`${s.column}\``).join(', ')} — ` +
        'unique at the time of writing.',
    );
  }
  if (numerics.length > 0) {
    out.push(
      `- Safe to aggregate: ${numerics.map((s) => `\`${s.column}\``).join(', ')}.`,
    );
  }
  const highSeverity = issues.filter((i) => i.severity === 'high');
  if (highSeverity.length > 0) {
    out.push(
      `- **Resolve ${highSeverity.length} high-severity issue(s) before relying on this data** ` +
        'for anything that matters.',
    );
  }
  out.push('- Re-run the pipeline rather than editing this output by hand, so it stays reproducible.');
  out.push('');

  return out.join(NL);
}
