import { compileTransform } from './transforms';
import type { Pipeline, PipelineStep } from './pipeline';

/**
 * Turn a pipeline into code the user can run without this app.
 *
 * This is the honesty check on the whole product: if a cleaning session cannot
 * leave the browser, it is a demo. The SQL export is generated by the same
 * compiler that executed the steps, so the emitted query is the query that ran
 * — not a reimplementation that can quietly disagree with it.
 */

export type ExportFormat = 'sql' | 'python' | 'dbt' | 'json';

const NL = String.fromCharCode(10);

function header(pipeline: Pipeline, comment: string): string {
  return [
    `${comment} ${pipeline.name} — generated by DataSweep Pro`,
    `${comment} ${pipeline.steps.length} step(s), recorded ${pipeline.createdAt}`,
    `${comment} Expects columns: ${pipeline.requiredColumns.join(', ')}`,
  ].join(NL);
}

/**
 * SQL, as a chain of CTEs.
 *
 * Each CTE is one step, so the exported query reads in the same order as the
 * ledger and a reviewer can delete a step by deleting a CTE.
 */
export function toSql(pipeline: Pipeline, sourceTable = 'raw_data'): string {
  if (pipeline.steps.length === 0) {
    return `${header(pipeline, '--')}${NL}${NL}SELECT * FROM ${sourceTable};`;
  }

  let previous = sourceTable;
  let columns = [...pipeline.requiredColumns];
  const ctes: string[] = [];

  pipeline.steps.forEach((step, index) => {
    const name = `step_${index + 1}_${step.operation}`;
    const compiled = compileTransform(
      { operation: step.operation, column: step.column, parameters: step.parameters },
      { sourceTable: previous, columns },
    );

    ctes.push(
      `-- ${compiled.description}${NL}` +
        `${name} AS (${NL}  ${compiled.sql.replace(new RegExp(NL, 'g'), NL + '  ')}${NL})`,
    );

    previous = name;
    columns = [...compiled.resultColumns];
  });

  return [
    header(pipeline, '--'),
    '',
    // WITH on its own line: the first CTE opens with a comment, and trailing it
    // after WITH reads as though the keyword were commented out.
    `WITH${NL}${ctes.join(`,${NL}`)}`,
    `SELECT * FROM ${previous};`,
  ].join(NL);
}

/** pandas equivalents, one statement per step. */
function pythonStep(step: PipelineStep): string[] {
  const col = step.column === null ? null : JSON.stringify(step.column);
  const p = step.parameters;

  switch (step.operation) {
    case 'remove_duplicates':
      return ['df = df.drop_duplicates()'];
    case 'trim_whitespace':
      return [`df[${col}] = df[${col}].astype("string").str.strip()`];
    case 'normalize_case': {
      const mode = String(p['mode'] ?? 'lower');
      const fn = mode === 'upper' ? 'upper' : mode === 'title' ? 'title' : 'lower';
      return [`df[${col}] = df[${col}].astype("string").str.${fn}()`];
    }
    case 'drop_column':
      return [`df = df.drop(columns=[${col}])`];
    case 'drop_rows_with_missing':
      return [
        `df = df[df[${col}].notna() & (df[${col}].astype("string").str.strip() != "")]`,
      ];
    case 'fill_missing': {
      if (String(p['strategy'] ?? '') === 'null_non_numeric') {
        return [
          `df[${col}] = pd.to_numeric(`,
          `    df[${col}].astype("string").str.replace(r"[^0-9.\\-]", "", regex=True),`,
          '    errors="coerce",',
          ')',
        ];
      }
      const value = JSON.stringify(String(p['value'] ?? 'Unknown'));
      return [
        `df[${col}] = df[${col}].astype("string").str.strip().replace("", pd.NA).fillna(${value})`,
      ];
    }
    case 'standardize_dates': {
      const dayFirst = p['dayFirst'] !== false ? 'True' : 'False';
      return [
        `parsed = pd.to_datetime(df[${col}], errors="coerce", dayfirst=${dayFirst}, format="mixed")`,
        `# Unparseable values keep their original text rather than becoming NaT.`,
        `df[${col}] = parsed.dt.strftime("%Y-%m-%d").fillna(df[${col}])`,
      ];
    }
    case 'parse_numbers':
      return [
        `df[${col}] = pd.to_numeric(`,
        `    df[${col}].astype("string").str.replace(r"[^0-9.\\-]", "", regex=True),`,
        '    errors="coerce",',
        ')',
      ];
    case 'clip_outliers':
      return [`df[${col}] = pd.to_numeric(df[${col}], errors="coerce").clip(${Number(p['lower'])}, ${Number(p['upper'])})`];
    case 'quarantine_rows':
      return [`df["__quarantined"] = df[${col}].notna()`];
    default:
      return [`# Unsupported in the Python export: ${String(step.operation)}`];
  }
}

export function toPython(pipeline: Pipeline, sourcePath = 'input.csv'): string {
  const body = pipeline.steps.flatMap((step, index) => [
    '',
    `# Step ${index + 1}: ${step.description}`,
    ...pythonStep(step),
  ]);

  return [
    header(pipeline, '#'),
    '',
    'import pandas as pd',
    '',
    '# Read everything as text, exactly as DataSweep does. Letting pandas infer',
    '# types here would coerce or drop the malformed values these steps fix.',
    `df = pd.read_csv(${JSON.stringify(sourcePath)}, dtype="string", keep_default_na=False)`,
    ...body,
    '',
    'df.to_csv("cleaned.csv", index=False)',
    `print(f"Wrote {len(df)} rows to cleaned.csv")`,
  ].join(NL);
}

/** A dbt model. The SQL is identical; only the wrapper differs. */
export function toDbt(pipeline: Pipeline, sourceRef = "ref('raw_data')"): string {
  const sql = toSql(pipeline, '__SOURCE__').replace(/__SOURCE__/g, `{{ ${sourceRef} }}`);

  return [
    '{{ config(materialized=\'table\') }}',
    '',
    sql.replace(/;$/, ''),
  ].join(NL);
}

export function toJson(pipeline: Pipeline): string {
  return JSON.stringify(pipeline, null, 2);
}

export function exportPipeline(pipeline: Pipeline, format: ExportFormat): string {
  switch (format) {
    case 'sql':
      return toSql(pipeline);
    case 'python':
      return toPython(pipeline);
    case 'dbt':
      return toDbt(pipeline);
    case 'json':
      return toJson(pipeline);
    default: {
      const exhaustive: never = format;
      throw new Error(`Unknown export format: ${String(exhaustive)}`);
    }
  }
}
